# Generated by Django 5.1.3 on 2024-11-29 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_author_news_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор новости'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(default='Пользователь', max_length=50, verbose_name='Источник'),
        ),
    ]
